version: '3.8'

services:
  remix-sample:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ..:/remix-sample:delegated
    - node_modules:/remix-sample/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@db:5432/remix-sample

  db:
    image: postgres:15.3-bookworm
    restart: unless-stopped
    volumes:
    - db_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  db_data:
  node_modules:
